name: Tag on Release

on:
  release:
    types: [published]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag Release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ github.event.release.tag_name }} -m "Release ${{ github.event.release.tag_name }}"
          git push origin ${{ github.event.release.tag_name }}
